server:
  address: 192.168.11.159
  port: 7090

management:
  security:
    enabled: false
  health:
    defaults:
      enabled: true

# Logging pattern for the console& Logging pattern for file
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} - %msg%n"
  file: "logs/console.log"
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace

# Mysql
spring:
  main:
    banner-mode: "off"
  http:
    encoding:
      charset: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mcmockup?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: 1212

mcc:
  elasticsearch:
    cluster-name: elasticsearch
    host: localhost
    port : 9200

# customer
---
spring:
  profiles: default
mcc:
  elasticsearch:
    executecmd: "elasticsearch.exe"
    executepath: "C:\\envai_program\\elasticsearch-6.1.3\\bin"
  logstash:
    executecmd: "logstash -f mcc.conf --config.reload.automatic"
    executepath: "C:\\envai_program\\logstash-6.1.3\\bin"
  filebeat:
    executecmd: "filebeat.exe -e -c filebeat.yml -d \"publish\""
    executepath: "C:\\envai_program\\filebeat-6.1.3-windows-x86_64"
  mccgateway:
    executecmd: "java -jar MccGateway-1.0-SNAPSHOT.jar --spring.profiles.active=local"
    executepath: "D:\\enavi_workspace\\MccGateway\\build\\libs"
  mccdaemon:
    executecmd: "MCCDaemon.exe"
    executepath: "C:\\service_program\\daemon"
  rabbitmq:
    executecmd: "rabbitmq-server.bat"
    executepath: "C:\\envai_program\\RabbitMQ Server\\rabbitmq_server-3.7.3\\sbin"
  kibana:
    executecmd: "kibana.bat"
    executepath: "C:\\envai_program\\kibana-6.1.3-windows-x86_64\\bin"
  mysql:
    executecmd: "net start Mysql_NEONEX"
    executepath: "C:\\WINDOWS\\system32"